roomapp/routes.py
from crypt import methods
from datetime import datetime
from multiprocessing import context
from flask import Blueprint, Flask, render_template, request, flash, make_response
from roomapp import db
from roomapp.models import Temperature, Users
from .forms import TempForm, UserForm, PasswordForm
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

app = Flask(__name__)

mainBP = Blueprint(
    'main',
    __name__,
    template_folder='templates'
)

@mainBP.app_errorhandler(404)
def not_found(error):
    return render_template('404.html', error = error)

@mainBP.app_errorhandler(500)
def server_error(error):
    return render_template('500.html', error = error)

@mainBP.route('/')
def index():
    context = {
        'title' : 'Home'
    }
    return render_template('index.html', **context)

@mainBP.route('/showtemperatures/')
def showtemp():
    data = Temperature.query.all()
    temps = [round(tempe.Temperature, 2) for tempe in data]
    labels = [str(item.Date) for item in data]
    values = [int(item) for item in temps]
    context = {
        'title' : 'Show Temperatures',
        'temps' : temps,
        'labels': labels,
        'values': values
    }
    return render_template('showtemp.html', **context)

@mainBP.route("/addtemp/", methods=['GET', 'POST'])
def addtemp():
    form = TempForm()
    if request.method == 'POST':
        datenow = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        temp =  Temperature(Date=datenow, DeviceID=int(form.DeviceID.data), Temperature=float(form.Temperature.data))
        try:
            db.session.add(temp)
            db.session.commit()
            return render_template('addtemp_confirmation.html')
        except Exception:
            db.session.rollback()
        
    return render_template('addtemp.html', form=form)

@mainBP.route("/addtempwtf/", methods=['GET', 'POST'])
def addtempwtf():
    temp_form = TempForm()
    if request.method == 'POST':
        datenow = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        temp =  Temperature(Date=datenow, DeviceID=int(temp_form.DeviceID.data), Temperature=float(temp_form.Temperature.data))
        try:
            db.session.add(temp)
            db.session.commit()
            return render_template('addtemp_confirmation.html')
        except Exception:
            db.session.rollback()
    context = {
        'title' : 'Add New Temperature',
        'temp_form' : temp_form
    }
        
    return render_template('addtempwtfquick.html', **context)

@mainBP.route('/adduser/', methods=['GET', 'POST'])
def adduser():
    user_form = UserForm()
    if user_form.validate_on_submit():
        user = Users.query.filter_by(email=user_form.email.data).first()
        flash("Form submitted")
        if user is None:
            hashed_pw = generate_password_hash(user_form.password_hash.data, "sha256")
            user = Users(name=user_form.Username.data, email=user_form.email.data, password_hash=hashed_pw)
            db.session.add(user)
            db.session.commit()
        username = user_form.Username.data
        user_form.username.data = ''
        user_form.email.data = ''
        user_form.password_hash.data = ''
    our_users = Users.query.order_by(Users.id)
    context = {
        'title' : 'User List',
        'user_form' : user_form,
        'our_users' : our_users
    }
    return render_template('adduser.html', **context)

@mainBP.route('/test_pw/', methods=['GET', 'POST'])
def test_pw():
    email = None
    password = None
    pw_to_check = None
    passed = None
    form  = PasswordForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password_hash.data
        #Limpia el formulario
        form.email.data = ''
        form.password_hash.data = ''

        pw_to_check = Users.query.filter_by(email=email).first()

        # Verificar password
        passed = check_password_hash(pw_to_check.password_hash, password)
    context = {
        'title' : 'Check Password',
        'form' : form,
        'email' : email,
        'password' : password ,
        'pw_to_check' : pw_to_check,
        'passed' : passed
    }
    return render_template("test_pw.html", **context)

# Seccion de documentos de flask

@mainBP.route('/createapp')
def crearapp():
    return render_template('crearapp.html')

@mainBP.route('/configfile')
def configfile():
    return render_template('configfile.html')

@mainBP.route('/modelsfile')
def modelsfile():
    return render_template('modelsfile.html')

@mainBP.route('/formsfile')
def formsfile():
    return render_template('formsfile.html')

@mainBP.route('/routesfile')
def routesfile():
    return render_template('routesfile.html')

#Seccion de modulos de flask

@mainBP.route('/notas/')
def notas():
    return render_template('notas.html')

@mainBP.route('/flaskcli')
def flaskcli():
    return render_template('flaskcli.html')

@mainBP.route('/filtros')
def filtros():
    return render_template('filtros.html')

@mainBP.route('/cookies')
def cookies():
    return render_template('cookies.html')

@mainBP.route('/session')
def session():
    return render_template('session.html')

# Seccion de ejercios de Flask

@mainBP.route('/restapi')
def restapi():
    return render_template('restapi.html')


# Seccion notas 

@mainBP.route('/request')
def request():
    return render_template('request.html')

@mainBP.route('/jsonify')
def jsonify():
    return render_template('jsonify.html')

@mainBP.route('/httprequest')
def httprequest():
    return render_template('httprequest.html')

@mainBP.route('/httpcodes')
def httpcodes():
    return render_template('httpcodes.html')


@mainBP.route('/consultadb')
def consultadb():
    return render_template('consultadb.html')

@mainBP.route('/sessionmaker')
def sessionmaker():
    return render_template('sessionmaker.html')

@mainBP.route('/jwt')
def jwt():
    return render_template('jwt.html')



@mainBP.route('/setcookie/')
def setcookie():
    resp = make_response("<h2>La cookie 'holacookie' se configuro")
    resp.set_cookie('holacookie', 'hola')
    return resp

@mainBP.route('/getcookie/')
def getcookie():
    cookie1 = request.cookies.get('holacookie')
    return(f"'holacookie' dice: {cookie1}")


app.register_blueprint(mainBP)

roomapp/templates/addtemp.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;">Temperature Input Form</h2>
    <form action="" method="post">
        <fieldset>
            <legend>Temperature Input Form</legend>
            {{ form.csrf_token }}
            <div style="font: size 20px; font-weight:bold; margin-left:150px">
                {{ form.DeviceID.label }} : {{ form.DeviceID }} <br>
                {% for error in form.DeviceID.erros %} 
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %} 
                <br>
                {{ form.Temperature.label }} : {{ form.Temperature }} <br>
                <br>
                {{ form.submit }}
            </div>
        </fieldset>
    </form>
{% endblock %}

roomapp/templates/addtemp_confirmation.html
{% extends 'base.html' %}

{% block content %} 
    <h3>Congrats Temperature saved</h3>
{% endblock %}

roomapp/templates/addtempwtfquick.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{ wtf.quick_form(temp_form) }}

</div>

{% endblock %}

roomapp/templates/adduser.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

{% for message in get_flashed_messages() %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    
{% endfor%}
<div class="b-example-divider"></div>

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-7 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 mb-3">Sing up for getting all the benefits</h1>
      <p class="col-lg-10 fs-4"></p>
    </div>
    <div class="col-md-10 mx-auto col-lg-5">
      <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
          {{ user_form.hidden_tag() }}

          <div class="form-floating mb-3">
            {{ user_form.Username(type="text", class="form-control", id="floatingInput", placeholder="username")}}
            {{ user_form.Username.label(for="floatingInput")}}
          </div>
          <div class="form-floating mb-3">
            {{ user_form.Email(type="email", class="form-control", id="floatingInput", placeholder="name@example.com") }}
            {{ user_form.Email.label(for="floatingEmail") }}
          </div>
          <div class="form-floating mb-3">
            {{ user_form.password_hash(type="password", class="form-control", id="floatingPassword", placeholder="Password") }}
            {{ user_form.password_hash.label(for="floatingPassword") }}
          </div>
          <div class="form-floating mb-3">
            {{ user_form.password_hash2(type="password", class="form-control", id="password_hash2", placeholder="Password") }}
            {{ user_form.password_hash2.label(for="password_hash2") }}
          </div>
          {{ user_form.submit(class="w-100 btn btn-lg btn-primary") }}
      </form>
    </div>
  </div>
</div>
<br><br><br>
<table class="table table-hover table-bordered table-striped">
    {%for user in our_users %}
    <tr>
        <td>{{ user.id }} - {{ user.name }} - {{ user.email }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

roomapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>{{ title }} | App</title>
    {% else %}
        <title>SmartRoom | App</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="{{url_for('static', filename='bootstrap-icons-1.9.1/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/navbar.css')}}" rel="stylesheet">

  </head>
  <body>
    <header>
    {% include 'navbar.html' %}
    </header>
    <main>
        {% block content %} 
        {% endblock %}
        <div class="b-example-divider"></div>

        <div class="container">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
              </a>
              <span class="mb-3 mb-md-0 text-muted">&copy; 2022 Company, Inc</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
              <li class="ms-3"><a class="text-muted" href="https://github.com/braulioarher"><i class="bi bi-github"></i></a></li>
              <li class="ms-3"><a class="text-muted" href="https://www.linkedin.com/in/braulioarcher/"><i class="bi bi-linkedin"></i></a></li>
              <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/braulioarcher/"><i class="bi bi-instagram"></i></a></li>
            </ul>
          </footer>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

roomapp/templates/consultadb.html
{% extends 'base.html' %}

{% block content %} 
<div class="container" style="width: 80%;">
    <article class="blog-post">
        <br>
        <h2>Notas y atajos para examen wings</h2>
        <br>
        <h3>Consultas SQL</h3>
        <p>A continuacion se muestran las consultas mas comunes a la hora de usar SQLAlchemy</p>
        <blockquote class="blockquote">
            <p>Consulta con oracion SQL</p>
        </blockquote>
        <code style="color: blue; font-size: 15px;">
            from model.webvul import Users <br>
            from sqlalchemy import exc <br>
            import sqlite3 <br>
            from __main__ import db <br><br>
            
            # Connects the database <br>
            db = sqlite3.connect('webvuldatabase.db') <br> <br>
        
            # Sql Statement: used to fetch data from database <br>
            get_user_query = "SELECT user_id, first_name, last_name FROM users WHERE `user_id` = '" + form_userid + "'" <br> <br>
            
            # returning the fetched data <br>
            sqli_output = db.cursor().execute(get_user_query).fetchall() <br>
            sqli_output = [Users(user_id=i[0], first_name=i[1], last_name=i[2]) for i in sqli_output] <br>
            return None if sqli_output == [] else sqli_output <br>
            
        </code>
        <br>
        <blockquote class="blockquote">
            <p>INSERT</p>
        </blockquote>
        <code style="color: blue; font-size: 15px;">
            person = Person(username="braulio", email="braulio.arher@gmail.com") <br>
            db.session.add(person) <br>
            db.session.commit() <br>
        </code>
        <br>
        <blockquote class="blockquote">
            <p>SELECT</p>
        </blockquote>
        <p>Hay tres formas para devolver informacion de la base de dartos: 1. Buscar/Recuperar/Devolver todos los registros desde una tabla en particulart usando <b><i>MyModel.query.all()</i></b> 2. Buscar/Recuperar/Devolver un solo registro basado en su primary key usando <b><i>MyModel.query.get(id)</i></b> 3. Buscar/Recuperar/Devolver un grupo de registros basado en su consulta <b><i>Person.query.filter_by(arg=value, ...)</i></b></p>
        <code style="color: blue; font-size: 15px;">
            # aqui es como se buscan todas las personas <br>
            all_people = Person.query.all() <br>
            all_people = list(map(lambda x: x.serialize(), all_people)) <br> <br>
            
            # aqui es como se busca un grupo de personas con name = alex <br>
            all_people = Person.query.filter_by(name='alex') <br>
            all_people = list(map(lambda x: x.serialize(), all_people)) <br> <br>
            
            # aquí es cómo se busca a una persona con id = 3 (solo funciona con las primary key) <br>
            person = Person.query.get(3) <br>
        </code>
        <br>
        <blockquote class="blockquote">
            <p>DELETE</p>
        </blockquote>
        <p>Todo lo que tiene que hacer es crear un nuevo objeto Person, agregarlo a la sesion de la base de datos y commit</p>
        <code style="color: blue; font-size: 15px;">
            Product.query.filter_by(product_id=product_id).delete() <br>
            db.session.commit() <br>
        </code>
        <br>
        <blockquote class="blockquote">
            <p>UPDATE</p>
        </blockquote>
        <p>Para actualizar primero necesitamos seleccionar el registro de la base de datos, luego puedes actualizar la propiedad que desses y hacer commit nuevamente</p>
        <code style="color: blue; font-size: 15px;">
            person = Person.query.get(3) <br>
            person.name = "Bob" <br>
            db.session.commit() <br>
        </code>
        <br>
        <p>La ruta regresa una respuesta con la informacion de dir y un codigo de respuesta</p>


    </article>
</div>
{% endblock %}

roomapp/templates/cookies.html
{% extends 'base.html' %}

{% block content %} 
<div class="container" style="width: 80%;">
    <article class="blog-post">
        <br>
        <h2>Cookies</h2>
        <br>
        <p>Una <b><i>cookie</i></b> se refiere a enviar informacion desde un servidor web y almacenar la informacion en la computadora del cliente dentro de un archivo. El principal objetivo de las cookies es rastraer la actividad del usuario en un sitio web para mejorar la experiencia de usuario</p>
        <h3>Cookies en Flask</h3>
        <p>En una aplicacion Flask, las <b><i>cookies</i></b> pueden ser accedidas desde un atributo de un objeto <b>request</b> el atributo <b><i>cookies</i></b> es un diccionario que contiene todas las variables y sus valores correspondientes que se transmiten por el cliente. Adicionalmente una <b><i>cookie</i></b> se puede establecer usando el metodo <b><i>set_cookie</i></b> en un objeto de respuesta HTML</p>
        <blockquote class="blockquote">
            <p>Configurando una cookie.</p>
        </blockquote>
        <code style="color: blue; font-size: 15px;">
            # Se declara la siguiente funcion para establecer la cookie usercount <br>
            # Si tratamos de acceder al URL /setcookie este establece el numero de usuarioas a usercount <br>
            @helloBP.route('/setcookie/') <br>
            def setcookie(): <br>
            &nbsp;&nbsp;&nbsp;&nbsp;nusers = User.query.count() <br>
            &nbsp;&nbsp;&nbsp;&nbsp;resp = make_response("&#60;h2&#62;'usercount' cookie is sucessfully set.&#60;/h2&#62;") <br>
            &nbsp;&nbsp;&nbsp;&nbsp;resp.set_cookie('usercount', str(nusers)) <br>
            &nbsp;&nbsp;&nbsp;&nbsp;return resp <br>
        </code>
        <br>
        <p>En el ejemplo anterior usamos el metodo <br><i>set_cookie()</i> la cual configura una cookie de nombre <b>usercount</b> la cual regresa una respuesta con la cookie creada</p>
        <blockquote class="blockquote">
            <p>Accediendo a la Cookie</p>
        </blockquote>
        <code style="color: blue; font-size: 15px;">
            #Se declara esta funcion para obtener la cookie usercount <br>
            @helloBP.route('/getcookie/') <br>
            def getcookie(): <br>
            &nbsp;&nbsp;&nbsp;&nbsp;usercount = request.cookies.get('usercount') <br>
            &nbsp;&nbsp;&nbsp;&nbsp;return (f"Values of 'usercount' is : {usercount}") <br>
        </code>
        <br>
        <p>En el ejemplo anterior definimos una ruta en <b><i>routes.py</i></b> donde cargamos la informacion de la cookie en una variable <i>usercount</i> esto lo logramos usando el metodo <b><i>request.cookies.get('cookiebane')</i></b> posterior a esto regresamos un string con el valor de dicha cookie</p>

        <p>Una nota importante es que podemos tener cuantas cookies como quedramos solo deben tener diferentes nombres y debemos de configurarlas en un ruta en especifico</p>
    </article>
    <nav class="blog-pagination" aria-label="Pagination">
        <a class="btn btn-outline-primary rounded-pill" href="{{ url_for('main.session') }}">Manejo de Session</a>
    </nav>
</div>
{% endblock %}

roomapp/templates/crearapp.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="width: 80%;">

      <article class="blog-post">
        <hr>
        <h2>Crear aplicacion Flask</h2>
        <p>En este sitio podras saber como crear una aplicacion Flask y la estructura de los elementos que la componen</p>
        <blockquote class="blockquote">
          <p>Requisitos.</p>
        </blockquote>
        <p>Para crear una aplicacion en Flas previamente se debe de tener instaldo el paquete de Flask en el entorno virtual esto lo podemos lograr usando el comando <b><i>pip install flask</i></b> una vez instalada la paquteria podemos crear una carpeta que incluya el archivo <b><i>__init__.py</i></b> o bien podemos crear un archivo llamado <b><i>main.py</i></b> este archivo sera la base de nuestra aplicacion dento de nuestra carpeta principal se puede crear sub carpetas como <b>templates</b> o <b>static</b> las cuales ayudan a tener mas orden en nustro proyecto adicional a las carpetas se pueden crear archivos como: <b><i>config.py</i></b>, <b><i>forms.py</i></b>, <b><i>models.py</i></b> y <b><i>routes.py</i></b> archivos los cuales ayudan a contener funciones y clases que le dan funcionalidades a nuestra aplicacion</p>
        <h3>Estructura de nuestra aplicacion</h3>
        <h6>foldername</h6>
        <p>| - <b><i>__init__.py</i></b></p>
        <p>| - <b><i>config.py</i></b></p>
        <p>| - <b><i>forms.py</i></b></p>
        <p>| - <b><i>models.py</i></b></p>
        <p>| - <b><i>routes.py</i></b></p>
        <p>| - <b><i>templates</i></b></p>
        <p>| - <b><i>static</i></b></p>

        <h3>Creado la app</h3>
        <p>Para crear la aplicacion como se menciono ateriormente se puede hacer de dos formas bastantes similares la diefencia radica en el archivo <b><i>__init__.py</i></b> tenemos que crear una funcion que regrese nuestra aplicacion mientras que al usar  archivo <b><i>main.py</i></b> debemos de crear los comando como se muestran a continuacion</p>
        <code style="color: blue; font-size: 15px;"> 
                from flask import Flask <br>
                from .config import BaseConfig <br>
                from flask_sqlalchemy import SQLAlchemy <br>
                from flask_migrate import Migrate <br><br>


                app = Flask(__name__)               #Hacemos una instancia para crear la app <br>
                app.config.from_object(BaseConfig)  #Cargamos las configuraciones de la app <br><br>
                bootstrap = Bootstrap(app) <br>
                db = SQLAlchemy(app) <br>
                migrate = Migrate(app, db) <br>
        </code>
        <br>
        <p>Una vez intanciadas nuestras variables de aplicacion podemos importar nuestra app desde nuestro archivo <b><i>main.py</i></b> usando <code>form foldername import app</code> de esta forma podemos exportar nuestra variable <b><i>FLASK_APP</i></b> a nuestra terminar usando el comando <code><b>export FLAS_APP=main.py</b></code></p>
        <p>La siguiente manera es similar solo creado la funcion <b><i>create_app</i></b> y retornando la variable app</p>
                <code style="color: blue; font-size: 15px;"> 
                from flask import Flask <br>
                from .config import BaseConfig <br>
                from flask_bootstrap import Bootstrap <br>
                from models import db <br> <br>

                def create_app(test_config=None) <br>
                &nbsp;&nbsp;&nbsp;&nbsp;app = Flask(__name__)               #Hacemos una instancia para crear la app <br>
                &nbsp;&nbsp;&nbsp;&nbsp;app.config.from_object(BaseConfig)  #Cargamos las configuraciones de la app <br><br>
                &nbsp;&nbsp;&nbsp;&nbsp;bootstrap = Bootstrap(app) <br>
                &nbsp;&nbsp;&nbsp;&nbsp;db.app = app <br>
                &nbsp;&nbsp;&nbsp;&nbsp;db.init_app(app) <br><br>

                &nbsp;&nbsp;&nbsp;&nbsp;return app <br>
        </code>
        <br>
        <p>De esta forma entonces podemos exportar nuestra variable <b><i>FLASK_APP</i></b> a nuestra terminar usando el comando <code><b>export FLAS_APP=foldername</b></code></p>

      <nav class="blog-pagination" aria-label="Pagination">
        <a class="btn btn-outline-primary rounded-pill" href="{{ url_for('main.configfile') }}">Archivo config.py</a>
      </nav>
        </article>
</div>
{% endblock %}

roomapp/templates/navbar.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">SmartRoom</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            DB Operations
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('main.addtemp') }}">Add Temperature</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.showtemp')}}">Show Temperatures</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{ url_for('main.addtempwtf') }}">Quick Forms Add Temp</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Acordeon Flask
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('main.crearapp') }}">Crear aplicacion</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.configfile') }}">Archivo config.py</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.modelsfile') }}">Archivo models.py</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.formsfile') }}">Archivo forms.py</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.routesfile') }}">Archivo routes.py</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{ url_for('main.notas') }}">Notas y atajos</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.flaskcli') }}">CLI de flask</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.filtros') }}">Filtros</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.cookies') }}">Cookies</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.session') }}">Session</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ejercicios Wings
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('main.restapi') }}">Wings RESTWebApi</a></li>
            <!-- <li><hr class="dropdown-divider"></li> -->
            <!-- <li><a class="dropdown-item" href="{{ url_for('main.request') }}">Notas y atajos wings</a></li> -->
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Notas y atajos
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('main.request') }}">flask.request</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.jsonify') }}">flask.jsonify</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.httprequest') }}">Peticiones HTTP</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.httpcodes') }}">Codigos de estado HTTP</a></li>

            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{ url_for('main.consultadb') }}">Consultas a DB</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.sessionmaker') }}">sessionmaker</a></li>
            <li><a class="dropdown-item" href="{{ url_for('main.jwt') }}">jwt</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>